# Octave Tutorial

## Basic Operations

In [2]:
% 基本数值运算
5+6

ans = 11


In [3]:
% 逻辑运算
1==2

ans = 0


In [4]:
A  = [1 2; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [5]:
V = 1:6

V =

   1   2   3   4   5   6



In [6]:
ones(2,3)

ans =

   1   1   1
   1   1   1



In [7]:
C = 2*ones(2,3)

C =

   2   2   2
   2   2   2



In [8]:
W = zeros(1,3)

W =

  0  0  0



In [9]:
% 生成随机数矩阵
rand(3,3)

ans =

   0.969180   0.024858   0.194031
   0.378550   0.190570   0.418047
   0.971377   0.356287   0.279650



In [10]:
% 高斯随机变量 / 正态分布的随机变量
w = randn(1,3)

w =

  -1.3312   1.2326   1.3387



## Moving Data Around

In [11]:
A = [1 2; 3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [13]:
sz = size(A)

sz =

   3   2



In [14]:
% 返回A矩阵的行数
size(A, 1)

ans = 3


In [15]:
% 返回A矩阵的列数
size(A, 2)

ans = 2


In [16]:
% 返回A矩阵的最大维度
length(A)

ans = 3


In [18]:
A = [1 10; 3 11; 5 12]

A =

    1   10
    3   11
    5   12



In [19]:
A = [A, [100; 101; 102]]

A =

     1    10   100
     3    11   101
     5    12   102



In [20]:
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
C = [A B]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

    1    2   11   12
    3    4   13   14
    5    6   15   16



In [21]:
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
C = [A; B]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

    1    2
    3    4
    5    6
   11   12
   13   14
   15   16



## Computing on Data

In [23]:
% 矩阵乘法
A = [1 2; 3 4; 5 6]
C = [1 1; 2 2]
AC = A*C

A =

   1   2
   3   4
   5   6

C =

   1   1
   2   2

AC =

    5    5
   11   11
   17   17



In [24]:
% 点乘运算
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
AB = A.*B

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

AB =

   11   24
   39   56
   75   96



In [25]:
% 矩阵平方
A = [1 2; 3 4; 5 6]
A2 = A.^2

A =

   1   2
   3   4
   5   6

A2 =

    1    4
    9   16
   25   36



In [26]:
% 倒数
V = [1;2;3]
V_ = 1./V

V =

   1
   2
   3

V_ =

   1.0000
   0.5000
   0.3333



In [27]:
log(V)

ans =

        0
   0.6931
   1.0986



In [28]:
exp(V)

ans =

    2.7183
    7.3891
   20.0855

